services:
  app:
    build:
      context: ../pharmastock-backend
      dockerfile: ../docker/Dockerfile
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    image: pharmastock-app
    container_name: pharmastock-app
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
    - ../pharmastock:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: pharmastock-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pharmastock
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  dbdata:

